### ISSUE TITLE
不支持Unix/Linux下的视频处理

### ISSUE THREAD

**Issue by Flowingsun007** [CharlesPikachu/Video-Downloader#10]
看了utils.py源码，发现230行默认用：`is_success = m3u8Parser().run`下载并解码，不成功，转而用：`os.system('ffmpeg.exe -i {} -c copy {}.....`下载，这个可执行的.exe只能在windows下使用，如果需要在Linux上用，需要改成`ffmpeg -i {} -c copy {}.....`

所以源码做一下如下改动，能支持多种系统，会好一些：
![屏幕截图](https://user-images.githubusercontent.com/28823622/68823541-0af44900-06cf-11ea-917c-57975ee77c73.png)

**Comment by CharlesPikachu** [comment]
OKOK，感谢建议，当时没考虑那么多，我马上修改一下~

**Comment by Flowingsun007** [comment]
好的麻烦了！
下载器很好用，谢谢：）
